import React from 'react'
import Head from 'next/head'
import Header from './partials/header';
import Sidebar from './partials/sidebar';
import Setting from './partials/setting';
import { useState } from 'react';
import { accountService } from '@/src/services';
import { ApiProvider } from '@/src/controller/apiContext';

// import "../../styles/assets/plugin/light-gallery/css/lightgallery.css"
// import "../../styles/assets//css/timetracker.style.min.css"
function Layout({children}) {
    const [toggleside, settoggleside] = useState(false);
    const [togglesetting, settogglesetting] = useState(false)
    return ( 
        <>
        <ApiProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
         <div id="timetracker-layout" className="theme-mist">
            <Sidebar toggleside={toggleside}/>
            <div className="main px-lg-4 px-md-4">  
                <Header toggleside={toggleside} settoggleside={settoggleside} togglesetting={togglesetting} settogglesetting={settogglesetting}/>
                <div className="body d-flex py-lg-3 py-md-2">
                <div className="container-xxl">
                    <div className="col-12">
                    {
                        children
                    }
                    </div>
                </div>
            </div>
                        
            </div>
        </div><Setting togglesetting={togglesetting} settogglesetting={settogglesetting}/>
       </ApiProvider></>
     );
}

export default Layout;